version: '3.7'

services:
  frontend:
    build:
      context: ../frontend
      target: build-stage
    command: npm run dev -- --host --port 80
    volumes:
      - ../frontend/src:/app/src
    environment:
      DEBUG: 1
    ports:
      - "8080:8080"

  song-stream:
    volumes:
      - "../song_streaming:/code"
    command: uvicorn src.streaming.main:app --host 0.0.0.0 --port 80 --proxy-headers --reload
    environment:
      DEBUG: 1
    ports:
      - "1337:80"

  song-details:
    volumes:
      - "../song_details:/code"
    command: python manage.py runserver 0.0.0.0:80
    environment:
     - DEBUG=1
    ports:
      - "1338:80"

  song-details-database:
    ports:
      - "5432:5432"
      - "27017:27017"

  song-details-database-pgadmin:
    image: dpage/pgadmin4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGADMIN_DEFAULT_EMAIL=aaa@aaa.aa
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "1339:80"