version: '3.7'

services:
  frontend:
    build:
      context: ../frontend
      target: production-stage

  song-stream:
    build:
      context: ../song_streaming
    volumes:
      - ../data/songs:/songs

  song-details:
    build:
      context: ../song_details
    command:
      - python -m uvicorn myproject.asgi:application

  api-gateway:
    hostname: gateway
    image: nginx
    volumes:
      - ../api_gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - song-stream
      - frontend

  song-details-database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PGPORT=27017
    volumes:
      - ../data/metadata/db:/var/lib/postgresql/data