version: '3'

services:
  katarynka-front:
    container_name: katarynka-front
    build:
      context: frontend
      target: build-stage
    command: npm run dev -- --host --port 80
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "8080:8080"

  katarynka-stream:
    container_name: katarynka-stream
    build:
      context: song_streaming
    volumes:
      - "./song_streaming:/code"
    environment:
      DEBUG: 1
      
  api-gateway:
    container_name: api-gateway
    hostname: gateway
    image: nginx
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - katarynka-stream
      - katarynka-front
