version: '3'

services:
  katarynka-front:
    container_name: katarynka-front
    build:
      context: frontend

  katarynka-stream:
    container_name: katarynka-stream
    build:
      context: song_streaming
      
  api-gateway:
    container_name: api-gateway
    hostname: gateway
    image: nginx
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - katarynka-stream
      - katarynka-front
