version: '3'

services:
  katarynka-front:
    build:
      context: ../frontend

  katarynka-stream:
    build:
      context: ../song_streaming
    volumes:
      - ../data/songs:/songs

  katarynka-song-details:
    build:
      context: ../song_details

  api-gateway:
    hostname: gateway
    image: nginx
    volumes:
      - ../api_gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - katarynka-stream
      - katarynka-front

  katarynka-song-details-database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ../data/metadata/db:/data/db