version: '3.7'

services:
  frontend:
    build:
      context: ../frontend
      target: build-stage
    command: npm run dev -- --host --port 80
    volumes:
      - ../frontend/src:/app/src
    environment:
      DEBUG: 1
    ports:
      - "8080:8080"

  song-stream:
    volumes:
      - "../song_streaming:/code"
    command: uvicorn src.streaming.main:app --host 0.0.0.0 --port 80 --proxy-headers --reload
    environment:
      DEBUG: 1
    ports:
      - "1337:80"

  song-details:
    volumes:
      - "../song_details:/code"
    command: python manage.py runserver 0.0.0.0:80
    environment:
     - DEBUG=1
     - MONGODB_USER=root
     - MONGODB_PASSWORD=example
    ports:
      - "1338:80"

  song-details-database:
    ports:
      - "27017:27017"
